spring:
  application:
    name: customer-service
server:
  port: ${PORT:8080} 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
     defaultZone: ${EUREKA_URL}/eureka/
  instance:
    securePortEnabled: true 
    securePort: ${PORT:8080}
    hostname: ${DOMAIN:localhost}
    homePageUrl: https://${eureka.instance.hostname}/